version: '2'

volumes:
 mongodb_data:

networks:
  core_network:
    driver: bridge
    driver_opts:     
      com.docker.network.bridge.name: corenet
    ipam:
      driver: default
      config:
        - subnet: 192.168.26.0/24
          gateway: 192.168.26.1
  rf_network:
    driver: bridge
    driver_opts:     
      com.docker.network.bridge.name: rf
    ipam:
      driver: default
      config:
        - subnet: 192.168.28.0/24
          gateway: 192.168.28.1


services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb
    networks:
      core_network:
        ipv4_address: 192.168.26.5

  webui:
    build: ./
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb/open5gs
    container_name: webui
    hostname: webui
    ports:
      - "3000:3000"
    volumes:
        - "./config:/usr/local/etc:z"
    entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_webui.sh"
    networks:
      core_network:
        ipv4_address: 192.168.26.6

  mongodbloader:
    image: mongo:latest
    depends_on:
      - webui
    environment:
      - DB_HOST=192.168.26.5
    volumes:
      - "./provisioning/db/run_db.sh:/tmp/run.sh:z"
      - "./provisioning/db/imsi1.json:/tmp/imsi1.json:z"
    entrypoint:
      - /bin/sh
      - /tmp/run.sh
    networks:
      core_network:
        ipv4_address: 192.168.26.19

  hss:
    build: ./
    depends_on:
      - mongodb
    container_name: hss
    hostname: hss
    entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_hss.sh"
    volumes:
      - "./config:/usr/local/etc:z"
    networks:
      core_network:
        ipv4_address: 192.168.26.10

  mme:
     build: ./
     depends_on:
       - hss
     container_name: mme
     hostname: mme
     entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_mme.sh"
     volumes:
      - "./config:/usr/local/etc:z"
     networks:
       core_network:
         ipv4_address: 192.168.26.20

  sgw:
     build: ./
     container_name: sgw
     hostname: sgw
     entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_sgw.sh"
     volumes:
      - "./config:/usr/local/etc:z"
     networks:
       core_network:
         ipv4_address: 192.168.26.30

  pgw:
     build: ./
     container_name: pgw
     hostname: pgw
     entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_pgw.sh"
     volumes:
      - "./config:/usr/local/etc:z"
     cap_add:
       -  NET_ADMIN
     devices:
       -  /dev/net/tun
     networks:
       core_network:
         ipv4_address: 192.168.26.40

  pcrf:
    build: ./
    depends_on:
       - mongodb
       - hss
    container_name: pcrf
    hostname: pcrf
    entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_pcrf.sh"
    volumes:
      - "./config:/usr/local/etc:z"
    networks:
       core_network:
         ipv4_address: 192.168.26.50

  enb:
    build: ./srsLTE
    container_name: enb
    ipc: shareable
    depends_on:
      - mme
    cap_add:
      - SYS_NICE
    networks:
      core_network:
         ipv4_address: 192.168.26.60
      rf_network:
         ipv4_address: 192.168.28.60
    volumes:
      - ./srsLTE:/config:z
    entrypoint:
      - /bin/sh
      - /config/run_enb.sh

  ue:
    container_name: ue
    build: ./srsLTE
    ipc: "container:enb" 
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    networks:
      rf_network:
          ipv4_address: 192.168.28.61
    depends_on:
      - enb
    volumes:
      - ./srsLTE:/config:z
    entrypoint:
      - /bin/sh
      - /config/run_ue.sh


